// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: instructors.sql

package database

import (
	"context"
)

const createInstructor = `-- name: CreateInstructor :one
INSERT INTO instructors (id, created_at, updated_at, email, instructor_name, password_hash)
VALUES (
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1,
    $2,
    $3
)
RETURNING id, created_at, updated_at, email, instructor_name, password_hash
`

type CreateInstructorParams struct {
	Email          string
	InstructorName string
	PasswordHash   string
}

func (q *Queries) CreateInstructor(ctx context.Context, arg CreateInstructorParams) (Instructor, error) {
	row := q.db.QueryRowContext(ctx, createInstructor, arg.Email, arg.InstructorName, arg.PasswordHash)
	var i Instructor
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.InstructorName,
		&i.PasswordHash,
	)
	return i, err
}

const removeInstructors = `-- name: RemoveInstructors :exec
DELETE FROM instructors
`

func (q *Queries) RemoveInstructors(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, removeInstructors)
	return err
}
