// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Session struct {
	ID         uuid.UUID
	CreatedAt  time.Time
	UpdatedAt  time.Time
	StartTime  time.Time
	EndTime    time.Time
	Instructor string
	Difficulty int32
}

type User struct {
	ID           uuid.UUID
	Name         sql.NullString
	CreatedAt    time.Time
	UpdatedAt    time.Time
	Email        string
	PasswordHash string
}
