// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package database

import (
	"context"
	"time"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (id, created_at, updated_at, start_time, end_time, instructor, difficulty)
VALUES (
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1,
    $2,
    $3,
    $4
)
RETURNING id, created_at, updated_at, start_time, end_time, instructor, difficulty
`

type CreateSessionParams struct {
	StartTime  time.Time
	EndTime    time.Time
	Instructor string
	Difficulty int32
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession,
		arg.StartTime,
		arg.EndTime,
		arg.Instructor,
		arg.Difficulty,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartTime,
		&i.EndTime,
		&i.Instructor,
		&i.Difficulty,
	)
	return i, err
}

const querySessionsDifficulty = `-- name: QuerySessionsDifficulty :many
SELECT id, created_at, updated_at, start_time, end_time, instructor, difficulty FROM sessions WHERE difficulty = $1
`

func (q *Queries) QuerySessionsDifficulty(ctx context.Context, difficulty int32) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, querySessionsDifficulty, difficulty)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartTime,
			&i.EndTime,
			&i.Instructor,
			&i.Difficulty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const querySessionsInstructor = `-- name: QuerySessionsInstructor :many
SELECT id, created_at, updated_at, start_time, end_time, instructor, difficulty FROM sessions WHERE instructor = $1
`

func (q *Queries) QuerySessionsInstructor(ctx context.Context, instructor string) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, querySessionsInstructor, instructor)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartTime,
			&i.EndTime,
			&i.Instructor,
			&i.Difficulty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeSessions = `-- name: RemoveSessions :exec
DELETE FROM sessions
`

func (q *Queries) RemoveSessions(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, removeSessions)
	return err
}
