@target_host = localhost
@api_token = replace-me
### GET to check API health
GET http://localhost:5000/api/health

### GET to check DB health
GET http://localhost:5000/api/db_health
Authorization: Bearer {{api_token}}

### GET request server for users
GET http://{{target_host}}:5000/api/users
Authorization: Bearer {{api_token}}

### POST request to create a user
POST http://{{target_host}}:5000/api/users
Content-Type: application/json
Authorization: Bearer {{api_token}}

{
  "name": "Kelly Cantrell",
  "username": "kelz",
  "email": "kelz@example.com"
}

### POST request to create a user
POST http://{{target_host}}:5000/api/users
Content-Type: application/json
Authorization: Bearer {{api_token}}

{
  "name": "Vis Telimus",
  "username": "vis",
  "email": "vis@example.com"
}

### POST request to create a user w/o token - should fail
POST http://{{target_host}}:5000/api/users
Content-Type: application/json

{
  "name": "Vis Telimus",
  "username": "vis",
  "email": "vis@example.com"
}

### POST request w/ missing data - should fail
POST http://{{target_host}}:5000/api/users
Content-Type: application/json
Authorization: Bearer {{api_token}}

{
  "email": "jane.doe@example.com"
}