// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, created_at, updated_at, email, password)
VALUES (
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1,
    $2
)
RETURNING id, created_at, updated_at, email, password
`

type CreateUserParams struct {
	Email    string
	Password string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Email, arg.Password)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.Password,
	)
	return i, err
}

const queryUser = `-- name: QueryUser :one
SELECT id, created_at, updated_at, email, password FROM users WHERE email = $1
`

func (q *Queries) QueryUser(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, queryUser, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.Password,
	)
	return i, err
}

const removeUsers = `-- name: RemoveUsers :exec
DELETE FROM users
`

func (q *Queries) RemoveUsers(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, removeUsers)
	return err
}

const updateUserInfo = `-- name: UpdateUserInfo :one
UPDATE users
SET email = $1,
    password = $2,
    updated_at = NOW()
WHERE id = $3
RETURNING id, created_at, updated_at, email, password
`

type UpdateUserInfoParams struct {
	Email    string
	Password string
	ID       uuid.UUID
}

func (q *Queries) UpdateUserInfo(ctx context.Context, arg UpdateUserInfoParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserInfo, arg.Email, arg.Password, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.Password,
	)
	return i, err
}
